### ISSUE TITLE
How to build lstm-parse?

### ISSUE THREAD

**Issue by xuanchien** [clab/stack-lstm-ner#1]
Hi,

I am looking for a way to compile lstm-parse. I have installed CNN but now I wonder how to compile lstm-parse.cc? It is unable to load the "cnn" library (ex: fatal error: 'cnn/training.h' file not found). I guess I need to set the path to CNN somehow but I don't know exactly. Could you please help?

Thank you in advance

**Comment by miguelballesteros** [comment]
Let me have a look and I'll let you know.

Miguel

**Comment by miguelballesteros** [comment]
Try this and let me know if it works:

The first time you clone the repository, you need to sync the cnn/ submodule.

git submodule init
git submodule update

mkdir build
cd build
cmake .. -DEIGEN3_INCLUDE_DIR=/path/to/eigen
make -j2

**Comment by xuanchien** [comment]
Thanks @miguelballesteros , I have managed to compile it. It follows basically the same steps you described above :). Anyway, thank you for your prompt response

**Comment by rohithkodali** [comment]
hi @xuanchien i'm trying to install on a couple of machines but i always has some issue, throwing a lot of unreadable error, i too follow the same as above, how you managed to install compile it.

**Comment by xuanchien** [comment]
@rohithkodali 
Can you describe more about the error? Please paste the log if possible. I just followed the instruction given on README

**Comment by rohithkodali** [comment]
ok here is the complete log file
[log.txt](https://github.com/clab/stack-lstm-ner/files/289612/log.txt)

here is my Cmakelist.txt file added --std=c++11 to existing one

PROJECT(cnn:parser)
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -funroll-loops -Wall -std=c++11 -Ofast -g -DEIGEN_FAST_MATH -march=native -lboost_serialization -lboost_program_options")

FIND_PACKAGE(Boost COMPONENTS program_options REQUIRED)
INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS})

ADD_EXECUTABLE(lstm-parse lstm-parse.cc)
target_link_libraries(lstm-parse cnn ${Boost_LIBRARIES})

**Comment by xuanchien** [comment]
I see that the error is related to Boost, have you installed Boost library?

**Comment by rohithkodali** [comment]
Yes I installed it using

Sudo apt-get install libboost-all-dev

On Monday 30 May 2016, Chien Tran notifications@github.com wrote:

> I see that the error is related to Boost, have you installed Boost library?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/clab/stack-lstm-ner/issues/1#issuecomment-222493982,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHCDjDL0GeZwqD0RVYEV7t5AZ-hUvNfJks5qGueFgaJpZM4IZ2eu
> .

## 

Best regards,
K.Rohith Gowtham

**Comment by miguelballesteros** [comment]
I think that you don't have the iostream boost library.

**Comment by miguelballesteros** [comment]
@rohithkodali  there was a missing file, I just pushed a new version, please try to clone again and compile again. 
Sorry about that. (I had it defined locally)
