### ISSUE TITLE
fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory

### ISSUE THREAD

**Issue by SeekPoint** [clab/stack-lstm-ner#10]
rzai@rzai00:~/prj/stack-lstm-ner/build$ cmake .. -DEIGEN3_INCLUDE_DIR=/usr/include/eigen3
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   program_options
--   serialization
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rzai/prj/stack-lstm-ner/build
rzai@rzai00:~/prj/stack-lstm-ner/build$ 
rzai@rzai00:~/prj/stack-lstm-ner/build$ 
rzai@rzai00:~/prj/stack-lstm-ner/build$ 
rzai@rzai00:~/prj/stack-lstm-ner/build$ make 
Scanning dependencies of target cnn
[  1%] Building CXX object cnn/cnn/CMakeFiles/cnn.dir/cfsm-builder.cc.o
In file included from /home/rzai/prj/stack-lstm-ner/cnn/cnn/cnn.h:13:0,
                 from /home/rzai/prj/stack-lstm-ner/cnn/cnn/cfsm-builder.h:6,
                 from /home/rzai/prj/stack-lstm-ner/cnn/cnn/cfsm-builder.cc:1:
/home/rzai/prj/stack-lstm-ner/cnn/cnn/tensor.h:22:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include <unsupported/Eigen/CXX11/Tensor>
                                          ^
compilation terminated.
make[2]: *** [cnn/cnn/CMakeFiles/cnn.dir/cfsm-builder.cc.o] Error 1
make[1]: *** [cnn/cnn/CMakeFiles/cnn.dir/all] Error 2
make: *** [all] Error 2
rzai@rzai00:~/prj/stack-lstm-ner/build$

**Comment by miguelballesteros** [comment]
??

**Comment by miguelballesteros** [comment]
if you don't provide more information, I'm closing this issue.

**Comment by SeekPoint** [comment]
I had done all steps in readme

when I do the 'make', i got the error.

the version of eigen I used is 3.0

**Comment by sagnik** [comment]
@loveJasmine  You need to have version 3.3 of eigen. See [here](http://eigen.tuxfamily.org/index.php?title=Tensor_support) `IMPORTANT NOTE: The current developement version of Eigen (post-3.2) supports Tensors. This support is experimental and a moving target.` Download the latest version of eigen.
