### ISSUE TITLE
Trainlog file is empty

### ISSUE THREAD

**Issue by svensy** [clab/stack-lstm-ner#16]
Hi Miguel,

Thanks for this great work!
I just trained this model on my own dataset.
`./lstm-parse -T train.parser -d dev.parser --hidden_dim 100 --lstm_input_dim 100 -w sskip.100.vectors --pretrained_dim 100 --rel_dim 20 --action_dim 20 --input_dim 100 -t -S -D 0.3 > logNERYesCharNoPosYesEmbeddingsD0.3.txt &`
After 305 epoches, I clicked Ctrl+C to stop training but it was still running so I closed terminal. But then I checked out file logNERYesCharNoPosYesEmbeddingsD0.3.txt and it is empty. Can I retrieve my trainlog? And how can I use the model I just trained to tag a raw sentence? Thank you so much!

Thang.

**Comment by miguelballesteros** [comment]
How is it possible that you know it trained during 315 epochs without log file?

You need to stop training when you see that your development scores do not improve after six hours .

For Tagging plain text... , just generate a new input file (in conll data format) *with no entities* and run the 2 scripts plus the system. It will output the prediction.

M.

**Comment by svensy** [comment]
Thanks for answering!
I saw it in terminal (running epoch 315) then I clicked Ctrl+C but it was still running. Can you tell me how to stop training correctly? After I exit terminal, the folder where I run terminal has 3 more files which are parser_nopos_2_100_100_20_100_12_20-pid8319.params, latest_model, and logNERYesCharNoPosYesEmbeddingsD0.3.txt. But logNERYesCharNoPosYesEmbeddingsD0.3.txt is empty. 
For tagging plain text, what are the 2 scripts plus the system? Thank you so much.

Thang.

**Comment by miguelballesteros** [comment]
You need to ctrl c twice. 

Try printing std::cerr into the log file  (with 2> instead of >)

The scripts are the same you used to generate your training file.

M.
