### ISSUE TITLE
question about building the project

### ISSUE THREAD

**Issue by SunSonia** [clab/stack-lstm-ner#19]
Hi，

When I built this project in vs2017，I found:
![image](https://user-images.githubusercontent.com/30561781/33940132-d38d67fc-e048-11e7-914a-605f169fe8a5.png)

it cant find the file(rules.ninja).

Should I install or download other files？

Thanks.

**Comment by miguelballesteros** [comment]
There is no such thing in the code. Make sure it is not something local you have.

M.
