### ISSUE TITLE
Unable to run Decoding process

### ISSUE THREAD

**Issue by xuanchien** [clab/stack-lstm-ner#2]
Hi,

I am trying to test `lstm-parse` with ConNLL 2003 dataset. I have successfully trained the model using the command written on this github's README. When I run the command for Decoding part, however, it does not work as I expected. Here is the output when running "Decoding process":

```
cnn] random seed: 2548792902
[cnn] allocating memory: 512MB
[cnn] memory allocation done.
COMMAND: ./lstm-parse -T NERdata/eng.train.parser -d NERdata/eng.testb.parser --hidden_dim 100 --lstm_input_dim 100 -w sskip.100.vectors --pretrained_dim 100 --rel_dim 20 --action_dim 20 --input_dim 100 -m latest_model -S
Unknown word strategy: STOCHASTIC REPLACEMENT
Writing parameters to file: parser_nopos_2_100_100_20_100_12_20-pid46975.params
done
SHIFT
REDUCE(ORG)
OUT
REDUCE(MISC)
REDUCE(PER)
REDUCE(LOC)
nactions:6
nwords:23624
0:
1:NNP'
2:VBZ'
3:JJ'
4:NN'
5:TO'
6:VB'
7:.'
8:CD'
9:DT'
10:VBD'
11:IN'
12:PRP'
13:NNS'
14:VBP'
15:MD'
16:VBN'
17:POS"
18:JJR'
19:"'
20:RB"
21:,'
22:FW'
23:CC'
24:RB'
25:WDT'
26:('
27:)'
28::'
29:PRP$'
30:RBR'
31:VBG'
32:EX'
33:WP'
34:WRB'
35:$'
36:RP'
37:NNPS'
38:SYM'
39:NNS"
40:RBS'
41:UH'
42:NNP"
43:PDT'
44:''"
45:VBZ"
46:LS'
47:VBP"
48:JJS'
49:WP$'
50:NN"
51:MD"
52:PRP"
53:VBD"
54:NN|SYM'
Loading from sskip.100.vectors with100 dimensions
REDUCE(ORG) :: 0
REDUCE(MISC) :: 1
REDUCE(PER) :: 2
REDUCE(LOC) :: 3
Number of words: 266598
Number of UTF8 chars: 85
libc++abi.dylib: terminating with uncaught exception of type boost::archive::archive_exception: input stream error
Abort trap: 6
```

Do you have any suggestion for resolving this issue?

Thank you in advance!

**Comment by Oneplus** [comment]
It seems you need to provide the path to the model file with -m option from
command line.

**Comment by xuanchien** [comment]
Hi @Oneplus , I do provide the model. You can see that it is the last param in my command (-m latest_model). The model is in the same folder with lstm-parse.

**Comment by Oneplus** [comment]
Oh, I see that. the "boost::archive::archive_exception: input stream error"
basically results from a broken file (like file not exists), So maybe you
can double check if the lastest_model is linked to the correct model file.
Or you can provide the absolute model path instead.

**Comment by miguelballesteros** [comment]
as @Oneplus says, this can happen by several reasons. One of them is that you do not have enough disk space to store the model, or that the model is not correctly linked to latest_model.

**Comment by xuanchien** [comment]
@Oneplus @miguelballesteros Thank you. I realized that the model after previous training was corrupted. After rerun the training process, it worked successfully.
