### ISSUE TITLE
How to stop trainning and how to evaluate the score?

### ISSUE THREAD

**Issue by lreaderl** [clab/stack-lstm-ner#25]
After epoch 157, F1 score keeps at 0.814097, so I use ctrl+c to stop training, but it still working. Finally, I use kill +9 to stop it, but the log file(logNERYesCharNoPosYesEmbeddingsD0.3.txt) is empty. What should I do to stop it correctly?
Another question, for evaluate, is the log file the predictive file? Should I type this:
```
python attach_prediction.py -p logNERYesCharNoPosYesEmbeddingsD0.3.txt -t /path/to/conll2003/test -o result.txt
  ./conlleval < result.txt
```
?

**Comment by miguelballesteros** [comment]
Training needs to be manually stopped. As for the rest I'm not sure I understand, please follow the instructions in the readme.

**Comment by miguelballesteros** [comment]
About the log file, the system prints in stderr
