### ISSUE TITLE
Dimensions of the Spelling Model

### ISSUE THREAD

**Issue by Cartus** [clab/stack-lstm-ner#26]
Hi,

For the spelling model:
`fw_char_lstm(LAYERS, LSTM_INPUT_DIM, LSTM_CHAR_OUTPUT_DIM/2, model)`
The input dimension of the forward char lstm is LSTM_INPUT_DIM, which is 60 here. 

`char_emb(model.add_lookup_parameters(CHAR_SIZE, {INPUT_DIM})),`
However, the dimension of the char embedding is INPUT_DIM, which is 32 here.

` Expression cj=lookup(*hg, char_emb, wjint);
 fw_char_lstm.add_input(cj);`
Then we have this, we look up cj (dimension is 32), then use it as input to the foward char lstm, whose input dimension is 60. 
Did I miss something here?

Thank you!

**Comment by miguelballesteros** [comment]
You need to use the command line instructions. Those are default dimensions that may not be correct.

**Comment by Cartus** [comment]
I see. Thank you so much!
May I ask normally how do you set the input and output dimension of spelling model for this task?

**Comment by miguelballesteros** [comment]
Take a look at the readme and command line instructions

**Comment by Cartus** [comment]
Thanks!
