### ISSUE TITLE
Compiler issue

### ISSUE THREAD

**Issue by rohithkodali** [clab/stack-lstm-ner#3]
Hi,
  I'm trying to install this tool but with any compiler the  program is not getting compiled, CN Ninstalled successfully but ner tools has the issue

here is the error with gcc

/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \

the other options i have tried are

g++
g++ -std=c++11
gcc -std=c++11

but none of them seems to compile the priogram

**Comment by miguelballesteros** [comment]
You need to have boost and eigen installed and follow the instructions in the readme.

**Comment by rohithkodali** [comment]
I have them installed will try again from the scratch.

**Comment by miguelballesteros** [comment]
Have you run cmake and make?

**Comment by rohithkodali** [comment]
yes, here is my compilation sequence

mkdir build
cd build
cmake .. -DEIGEN3_INCLUDE_DIR=/home//speech/development/NER/stack-lstm-ner/cnn/eigen/
make

**Comment by miguelballesteros** [comment]
Does cmake find  boost?

**Comment by miguelballesteros** [comment]
It should work... I just tried locally with the latest version

**Comment by rohithkodali** [comment]
i tried on two machines, on both i have the same issue, i guess something more has to be done apart from readme.

**Comment by rohithkodali** [comment]
yes cmake find boost while installing CNN toolkit, here is the log

-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   program_options
--   regex
--   serialization
-- BACKEND not specified, defaulting to eigen.
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/speech/development/NER/stack-lstm-ner/cnn/build

**Comment by miguelballesteros** [comment]
make -j2 after that?

**Comment by rohithkodali** [comment]
yes make -j 2 for cnn worked well without any error and i also did sudo make install,   this installed all the libraries.

on ner-system  this is what i did 

mkdir build
cd build
cmake .. -DEIGEN3_INCLUDE_DIR=/home//speech/development/NER/stack-lstm-ner/cnn/eigen/
make

at make it throw some hundreds of errors after the above error

**Comment by rohithkodali** [comment]
if you want to check it deeply i can provide my system access if needed.

**Comment by miguelballesteros** [comment]
Not sure what is going one but cnn is a submodule here. Just create a folder, git clone, follow the steps  (submodule) and run cmake and make -j2

**Comment by rohithkodali** [comment]
can you send me the cpp compiler version in your system, that seems to have
the problem.

On Sat, May 28, 2016 at 4:22 PM, Miguel Ballesteros <
notifications@github.com> wrote:

> Not sure what is going one but cnn is a submodule here. Just create a
> folder, git clone, follow the steps (submodule) and run cmake and make -j2
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/clab/stack-lstm-ner/issues/3#issuecomment-222302499,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHCDjBEagGccCQ8_nfpnKJXQ3VoN_Lx-ks5qGB5xgaJpZM4IpC7A
> .

## 

Best regards,
K.Rohith Gowtham

**Comment by miguelballesteros** [comment]
I have compiled this with many different versions of gcc. 4.84. 5.3.0. 4.9.1.

Do you have the boost development libraries?

**Comment by miguelballesteros** [comment]
http://stackoverflow.com/questions/1030169/easy-way-pull-latest-of-all-submodules

Try this after git submodule init and after git submodule update

**Comment by miguelballesteros** [comment]
@rohithkodali  there was a missing file, I just pushed a new version, please try to clone again and compile again. 
Sorry about that. (I had it defined locally)
