### ISSUE TITLE
Can you share dataset?

### ISSUE THREAD

**Issue by zero76114** [clab/stack-lstm-ner#5]
Dear Friend,

I saw in README  the Dataset & Preprocessing are in /usr0/home/kkawakam/conll2003
But, I dont know how i can download. Please help me? I want to try run this implementation.

Thank you.

**Comment by miguelballesteros** [comment]
The dataset is conll2002 (or 2003), take a look here: http://www.cnts.ua.ac.be/conll2002/ner/

**Comment by zero76114** [comment]
Many thanks.
