### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by Marhabibi** [clab/stack-lstm-ner#6]
Hello,

I tried to do training using the sample "example.conll-2003". But I have received the following error. Would you please help me?

~/LSTM/stack-lstm-ner-master/build7/ner-system# ./lstm-parse -T /root/LSTM/stack-lstm-ner-master/ner-system/sample/sample.parser --hidden_dim 100 --lstm_input_dim 100 -w sskip.100.vectors --pretrained_dim 100 --rel_dim 20 --action_dim 20 --input_dim 100 -t -S -D 0.3 > logNERYesCharNoPosYesEmbeddingsD0.3.txt
[cnn] random seed: 1191923413
[cnn] allocating memory: 512MB
[cnn] memory allocation done.
COMMAND: ./lstm-parse -T /root/LSTM/stack-lstm-ner-master/ner-system/sample/sample.parser --hidden_dim 100 --lstm_input_dim 100 -w sskip.100.vectors --pretrained_dim 100 --rel_dim 20 --action_dim 20 --input_dim 100 -t -S -D 0.3
Unknown word strategy: STOCHASTIC REPLACEMENT
Writing parameters to file: parser_nopos_2_100_100_20_100_12_20-pid91809.params
done
SHIFT
REDUCE(PER)
OUT
REDUCE(LOC)
REDUCE(MISC)
REDUCE(ORG)
nactions:6
nwords:47
0:
1:NNP'
2:VBD'
3:TO'
4:.'
5:VBG'
6:VB'
7:RB'
8:IN'
9:DT'
10:NN'
11:,'
12:PRP$'
13:JJ'
14:CC'
15:WRB'
16:CD'
Loading from sskip.100.vectors with100 dimensions
REDUCE(PER) :: 0
REDUCE(LOC) :: 1
REDUCE(MISC) :: 2
REDUCE(ORG) :: 3
Number of words: 243052
Number of UTF8 chars: 47
terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::bad_any_cast >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)

**Comment by miguelballesteros** [comment]
Please try to run the command as shown in the wiki (you do not seem to have a development set)

./lstm-parse -T conll2003/train.parser -**d conll2003/dev.parser** --hidden_dim 100 --lstm_input_dim 100 -w sskip.100.vectors --pretrained_dim 100 --rel_dim 20 --action_dim 20 --input_dim 100 -t -S -D 0.3 > logNERYesCharNoPosYesEmbeddingsD0.3.txt &
