### ISSUE TITLE
Why no B- tag?

### ISSUE THREAD

**Issue by xuanchien** [clab/stack-lstm-ner#8]
Hi, I have just realized that this script only generates I- or O tag. There are no B- tags in the output. Is there any reason for this? Since I need B- tag as well, how should I modify this code?

Thanks in advance!

**Comment by miguelballesteros** [comment]
we didn't need that for the experiments, but you are more than welcome to modify the script to output that. You don't need to change the cpp code, I believe.

Thanks!
